name: "Release"

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Tag
        if: github.event.pull_request.merged
        id: tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
          release_strategy: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        if: github.event.pull_request.merged
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: ${{ steps.tag.outputs.tag }}
          draft: false
          prerelease: false
          body: |
            To see the changelog, [here](https://github.com/davivienda-colombia/davi-coe-aws-reusable-pipeline/blob/main/CHANGELOG.md).

  generate-changelog:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs:
      - tag
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true
        token: ${{ secrets.TOKEN_GITHUB }}
    - name: "✏️ Generate Release Changelog"
      uses: janheinrichmerker/action-github-changelog-generator@v2.4
      with:
        token: ${{ secrets.TOKEN_GITHUB }}
    - name: 🚀 Push Changelog
      run: |
        git config --local user.name github-actions
        git config --local user.email github-actions@github.com
        git add CHANGELOG.md
        git commit -m "🤖 Auto generate changelog"
        git push
